### ISSUE TITLE
Prevent emoji approvals from bots

### ISSUE THREAD

**Issue by srtfisher** [alleyinteractive/hubot-code-review#43]
This pull request was 'approved' in Alleybot because Netlify commented on the PR with an Emoji

https://github.com/alleyinteractive/mantle-docs/pull/1

**Comment by benpbolton** [comment]
hrmmm...  this might be trivially solved by unsetting this 'ole thing: `HUBOT_CODE_REVIEW_EMOJI_APPROVE`
